In [16]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and result.

import numpy as np
import pandas as pd
from IPython.display import display


# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [17]:
import numpy as np

arr = np.zeros(10, dtype=int)
arr[4]=1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


### 2. Create a 4x4 matrix with values ranging from 0 to 15.

In [18]:
import numpy as np

matrix = np.arange(16).reshape(4,4)
print(matrix)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [19]:
import numpy as np

# Define the given arrays
arr1 = np.array([[41, 30, 10], [6, 35, 23], [23, 9, 10]])
arr2 = np.array([[4, 29, 2], [5, 13, 3], [24, 16, 7]])

# Perform element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2  # Ensures element-wise division

# Print results
print("Element-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)


Element-wise Addition:
 [[45 59 12]
 [11 48 26]
 [47 25 17]]

Element-wise Subtraction:
 [[37  1  8]
 [ 1 22 20]
 [-1 -7  3]]

Element-wise Multiplication:
 [[164 870  20]
 [ 30 455  69]
 [552 144  70]]

Element-wise Division:
 [[10.25        1.03448276  5.        ]
 [ 1.2         2.69230769  7.66666667]
 [ 0.95833333  0.5625      1.42857143]]


### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [20]:
import numpy as np

# Given array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Extract elements from index 2 to 6 (excluding index 6)
sliced_arr = arr[2:6]

print(sliced_arr)


[30 40 50 60]


### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [21]:
import numpy as np

# Define the given array
arr = np.array([[15, 18, 20], 
                [15, 30, 8], 
                [25, 30, 60]])

# Compute mean, sum, and max
mean_value = round(np.mean(arr), 2)  # Round to 2 decimal places
sum_value = np.sum(arr)
max_value = np.max(arr)

# Print results
print("3×3 Array:\n", arr)
print("\nMean:", mean_value)
print("Sum:", sum_value)
print("Max Value:", max_value)


3×3 Array:
 [[15 18 20]
 [15 30  8]
 [25 30 60]]

Mean: 24.56
Sum: 221
Max Value: 60


# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [22]:
import pandas as pd

# Define data and index labels
data = [10, 20, 30, 40, 50]
index_labels = ['a', 'b', 'c', 'd', 'e']

# Create the Pandas Series
series = pd.Series(data, index=index_labels)

# Display the Series
print(series)


a    10
b    20
c    30
d    40
e    50
dtype: int64


### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [ ]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('data.csv')

# Display the DataFrame
print(df)

      Name  Age  Salary
0   Suresh   21   58000
1    Sagar   25  452320
2    Alice   40   50000
3      Bob   37   45000
4  Charlie   35   60000


### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [35]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('data.csv')

# Select the first three rows
first_three_rows = df.head(3)

# Alternatively, you can slice it directly like this:
# first_three_rows = df[:3]

# Display the selected rows
print(first_three_rows)


     Name  Age   Score
0  Suresh   21   58000
1   Sagar   25  452320
2   Alice   40   50000


### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [25]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('data.csv')

# Calculate the tax (10% of Salary)
df['Tax'] = df['Salary'] * 0.10

# Display the DataFrame with the new "Tax" column
print(df)


      Name  Age  Salary      Tax
0   Suresh   21   58000   5800.0
1    Sagar   25  452320  45232.0
2    Alice   40   50000   5000.0
3      Bob   37   45000   4500.0
4  Charlie   35   60000   6000.0


#### Filter the dataframe by the column "age" whereby the age is above 36 years

In [26]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('data.csv')

# Filter the DataFrame for rows where "Age" is above 36
filtered_df = df[df['Age'] > 36]

# Display the filtered DataFrame
print(filtered_df)


    Name  Age  Salary
2  Alice   40   50000
3    Bob   37   45000


# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [27]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()

Region  Sales
0  North   1000
1  South   1500
2  North   1200
3   West   1800
4  South   1300

In [28]:
import pandas as pd

# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})

# Compute total sales per region
total_sales = sales_data.groupby('Region')['Sales'].sum()

# Compute mean sales per region
mean_sales = sales_data.groupby('Region')['Sales'].mean()

# Display results
print("Total Sales per Region:\n", total_sales)
print("\nMean Sales per Region:\n", mean_sales)


Total Sales per Region:
 Region
North    2200
South    2800
West     3500
Name: Sales, dtype: int64

Mean Sales per Region:
 Region
North    1100.0
South    1400.0
West     1750.0
Name: Sales, dtype: float64


### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [ ]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

display(customers.head(2), orders.head(2))

In [39]:
import pandas as pd


# Sample orders DataFrame
orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

# Merge the customers and orders DataFrames on CustomerID
merged_data = pd.merge(customers, orders, on='CustomerID')

# Display the merged data
print(merged_data)


   CustomerID CustomerName  OrderID  Amount
0           1        Alice      101     250
1           2          Bob      102     400
2           2          Bob      103     600
3           4        David      104     150


### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [31]:
# NB: No test for this. Just an exercise for you to play around with
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

display(employees.head(2), departments.head(2))

EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2

DeptID DeptName
0       1       HR
1       2  Finance

In [32]:
import pandas as pd

# Sample employees DataFrame
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

# Sample departments DataFrame
departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

# Perform a left join between employees and departments on DeptID
merged_data = pd.merge(employees, departments, on='DeptID', how='left')

# Display the merged data
print(merged_data)


   EmpID EmpName  DeptID DeptName
0    101    John       1       HR
1    102    Jane       2  Finance
2    103   Alice       2  Finance
3    104     Bob       3      NaN


### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [33]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

Region Product  Sales
0  North       A    200
1  North       B    300

In [34]:
import pandas as pd

# Sample sales data
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

# Create the pivot table
sales_pivot = sales_pivot_data.pivot_table(values="Sales", index="Region", columns="Product", aggfunc="sum")

# Display the pivot table
print(sales_pivot)


Product    A    B
Region           
North    200  300
South    150  400
West     250  500
